org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.21-beta
neo_version_range=[26.1.2.0-beta,)

ae2_version=26.1.10-beta
ae2_version_range=[26.1.6-alpha,)

mod_id=ae2throughputmonitor
mod_name=AE2 System Throughput Monitor
mod_url=https://github.com/morris-labs/ae2-system-throughput-monitor
mod_license=MIT
mod_issue_tracker=https://github.com/morris-labs/ae2-system-throughput-monitor/issues
mod_version=26.1.2-1.0.0
mod_group_id=dev.morrislabs
mod_authors=MorrisLabs
mod_description=Adds a cable-face part that shows all items flowing through an AE2 network, with per-item produced and consumed rates.
